package heroes

// MockRaces is a sample collection of races. Will be useful for testing later.
var MockRaces = []Race{
	{
		ID:          1,
		Name:        "Human",
		Description: "We all understand the concept of a human. Lives in cities or whatever. Obs: plays with any classes.",
		BaseAttributes: Attribute{
			Strength:     3,
			Agility:      3,
			Intelligence: 3,
			Willpower:    3,
		},
		StartingSkills:     []Skill{},
		AvailableSkills:    []Skill{},
		RecommendedClasses: MockClasses,
	},
	{
		ID:          2,
		Name:        "Elf",
		Description: "Pointy ears and snob noses. Cunning. Lives in forests.",
		BaseAttributes: Attribute{
			Strength:     2,
			Agility:      4,
			Intelligence: 3,
			Willpower:    3,
		},
		StartingSkills:     []Skill{},
		AvailableSkills:    []Skill{},
		RecommendedClasses: []Class{MockClasses[1]},
	},
	{
		ID:          3,
		Name:        "Dwarf",
		Description: "Small, strong and bearded. Likes mountains and steel.",
		BaseAttributes: Attribute{
			Strength:     4,
			Agility:      2,
			Intelligence: 3,
			Willpower:    3,
		},
		StartingSkills:     []Skill{MockSkills[0]},
		AvailableSkills:    []Skill{},
		RecommendedClasses: []Class{MockClasses[0]},
	},
}

// MockClasses is a sample collection of classes. Will be useful for testing later.
var MockClasses = []Class{
	{
		ID:          1,
		Name:        "Warrior",
		Description: "Powerful fighters that excel in tatical combat.",
		BonusAttributes: Attribute{
			Strength:     1,
			Agility:      1,
			Intelligence: 0,
			Willpower:    0,
		},
		Role: Fighter,
		Proficiencies: []Proficiency{
			{ID: 1, Name: SimpleWeapons},
			{ID: 2, Name: ComplexWeapons},
		},
		StartingSkills:  []Skill{},
		AvailableSkills: []Skill{MockSkills[1]},
	},
	{
		ID:          2,
		Name:        "Thief",
		Description: "Elusive adventures capable of stealing things and pick locks without being noticed.",
		BonusAttributes: Attribute{
			Strength:     0,
			Agility:      1,
			Intelligence: 1,
			Willpower:    0,
		},
		Role: Dexterous,
		Proficiencies: []Proficiency{
			{ID: 1, Name: SimpleWeapons},
			{ID: 5, Name: Pickpocket},
		},
		StartingSkills:  []Skill{},
		AvailableSkills: []Skill{},
	},
	{
		ID:          3,
		Name:        "Wizard",
		Description: "Arcane conjurers that can alter the tide of events with magic.",
		BonusAttributes: Attribute{
			Strength:     0,
			Agility:      0,
			Intelligence: 1,
			Willpower:    1,
		},
		Role: Spellcaster,
		Proficiencies: []Proficiency{
			{ID: 1, Name: SimpleWeapons},
			{ID: 3, Name: CastMagic},
			{ID: 4, Name: ReadMagic},
		},
		StartingSkills:  []Skill{},
		AvailableSkills: []Skill{MockSkills[2], MockSkills[3]},
	},
}

// MockSkills is a sample collection of skills. Will be useful for testing later.
var MockSkills = []Skill{
	{
		ID:                1,
		Name:              "Mountain Vigor",
		Description:       "You are immune to poisoning and can rol 3d6 when testing STR to resist fatigue.",
		Bonus:             "",
		Mana:              "",
		DifficultyType:    Auto,
		Difficulty:        "",
		Activation:        Passive,
		Source:            FromRace,
		Type:              Characteristic,
		LevelRequirement:  None,
		SkillRequirements: []Skill{},
		Observations:      "",
	}, {
		ID:                2,
		Name:              "War Cry",
		Description:       "You unleashe a fervorous scream that motiates your allies. You and them receive +1 in every roll until the end of the turn.",
		Bonus:             "This bonus is not cummulative.",
		Mana:              "10",
		DifficultyType:    Auto,
		Difficulty:        "",
		Activation:        Action,
		Source:            FromClass,
		Type:              Ability,
		LevelRequirement:  None,
		SkillRequirements: []Skill{},
		Observations:      "",
	}, {
		ID:                3,
		Name:              "Hellfire",
		Description:       "You engulf a 4m ground area in flames. Everyone making contact will take 10 damage (fire) and another 10 damage (fire) per subsequent round they remain there. Lasts for 3 rounds.",
		Bonus:             "Must be cast with a staff.",
		Mana:              "30",
		DifficultyType:    Fixed,
		Difficulty:        "12",
		Activation:        Action,
		Source:            FromClass,
		Type:              Spell,
		LevelRequirement:  None,
		SkillRequirements: []Skill{},
		Observations:      "",
	},
	{
		ID:                4,
		Name:              "Hellfire II",
		Description:       "You engulf a 4m diameter ground area in flames and it starts raining fire. Everyone inside will take 20 damage (fire) and another 20 damage (fire) per subsequent round they remain there. Lasts for 3 rounds.",
		Bonus:             "Must be cast with a staff.",
		Mana:              "40",
		DifficultyType:    Fixed,
		Difficulty:        "12",
		Activation:        Action,
		Source:            FromClass,
		Type:              Spell,
		LevelRequirement:  Advanced,
		SkillRequirements: []Skill{},
		Observations:      "",
	},
	{
		ID:                5,
		Name:              "Apprentice of [class]",
		Description:       "Immediately choose a different class than yours when acquiring this skill. You gain all of its proficiencies and can acquire its skills as of your own.",
		Bonus:             "",
		Mana:              "",
		DifficultyType:    Auto,
		Difficulty:        "",
		Activation:        Passive,
		Source:            Base,
		Type:              Technique,
		LevelRequirement:  None,
		SkillRequirements: []Skill{},
		Observations:      "You class is still considered to be your main class for any in-game purposes.",
	},
}
